services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsletter
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
